baseurl = "puzzle-in-a-mug.netlify.app/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "The Puzzle in a Mug"
theme = "hugo-universal-theme"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = true
# number of words of summarized post content (default 70)
summaryLength = 20
# Enable comments by entering your Disqus shortname
disqusShortname = "andersonmdcanteli"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    title = 'The Puzzle ina Mug'
    weight = 1
    [languages.pt-br.params]
      subtitle = ''
      # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
      style = "turquoise"
      # Format dates with Go's time formatting
      date_format = "2 January 2006"   
      copyright = "Copyright (c) 2023 - 2023, The PuZZle in a Mug; Todos os direitos reservados."
      

    [languages.pt-br.menu]
      [[languages.pt-br.menu.logo]]
              pageRef = '/'
      [[languages.pt-br.menu.main]]
              name = 'Home'
              url = '/'
              weight = 1
      [[languages.pt-br.menu.main]]
              name = 'Blog'
              pageRef = '/blog'
              weight = 2
      [[languages.pt-br.menu.main]]
              name = 'Contato'
              pageRef = '/contact'
              weight = 10
      [[languages.pt-br.menu.main]]
              name = 'Sobre'
              pageRef = '/about'
              weight = 20      
      [[languages.pt-br.menu.topbar]]
          weight = 1
          name = "Whatsapp"
          url = "https://wa.me/+5541996808012"
          pre = "<i class='fab fa-2x fa-whatsapp'></i>"   
      [[languages.pt-br.menu.topbar]]
          weight = 2
          name = "GitHub"
          url = "https://github.com/puzzle-in-a-mug"
          pre = "<i class='fab fa-2x fa-github'></i>"   
      [[languages.pt-br.menu.topbar]]
          weight = 3
          name = "YouTube"
          url = "https://www.youtube.com/channel/UCf96X2h-DrdY4Oc615fZBew"
          pre = "<i class='fab fa-2x fa-youtube'></i>"             
      [[languages.pt-br.menu.topbar]]              
          weight = 4
          name = "Facebook"
          url = "https://www.facebook.com/canteli2207"
          pre = "<i class='fab fa-2x fa-facebook'></i>"              
      [[languages.pt-br.menu.topbar]]              
          weight = 5
          name = "Email"
          url = "mailto:andersonmdcanteli@gmail.com"
          pre = "<i class='fas fa-2x fa-envelope'></i>"       
          

              
  [languages.en]
    contentDir = 'content/en'
    disabled = true
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'The Puzzle in a Mug'
    weight = 2
    [languages.en.params]
      # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
      style = "red"    
      subtitle = ''
      # Format dates with Go's time formatting
      date_format = "January 2, 2006"     
      copyright = "Copyright (c) 2023 - 2023, The PuZZle in a Mug; all rights reserved."
    [languages.en.menu]
      [[languages.en.menu.main]]
              name = 'Home'
              pageRef = '/'
              weight = 1
      [[languages.en.menu.main]]
              name = 'Blog'
              pageRef = '/blog'
              weight = 2
      [[languages.en.menu.main]]
              name = 'Contact'
              pageRef = '/contact'
              weight = 10
      [[languages.en.menu.main]]
              name = 'About'
              pageRef = '/about'
              weight = 20      
      [[languages.en.menu.topbar]]
          weight = 1
          name = "Whatsapp"
          url = "https://wa.me/+5541996808012"
          pre = "<i class='fab fa-2x fa-whatsapp'></i>"   
      [[languages.en.menu.topbar]]
          weight = 2
          name = "GitHub"
          url = "https://github.com/puzzle-in-a-mug"
          pre = "<i class='fab fa-2x fa-github'></i>"   
      [[languages.en.menu.topbar]]
          weight = 3
          name = "YouTube"
          url = "https://www.youtube.com/channel/UCf96X2h-DrdY4Oc615fZBew"
          pre = "<i class='fab fa-2x fa-youtube'></i>"             
      [[languages.en.menu.topbar]]              
          weight = 4
          name = "Facebook"
          url = "https://www.facebook.com/canteli2207"
          pre = "<i class='fab fa-2x fa-facebook'></i>"              
      [[languages.en.menu.topbar]]              
          weight = 5
          name = "Email"
          url = "mailto:andersonmdcanteli@gmail.com"
          pre = "<i class='fas fa-2x fa-envelope'></i>"            
      
      
      
      




# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false




[params]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    viewMorePostLink = "/blog/"
    author = "Anderson Canteli"
    defaultKeywords = ["dados", "puzzle"]
    mainSections = ["blog"]
    defaultDescription = """"Why is it called Puzzles?" That's the puzzle"""

    # Social media
    facebook_site = "https://www.facebook.com/canteli2207" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/banners/banner-1.jfif"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "25.4372"
    longitude = "49.2700"



    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = false
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = """<span>Why is it called Puzzles? Why a mug??</span>
    <br>
    <span class="transparent">That's the puzzle!!!</span>"""
    



    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "The Puzzle in a Mug"
    contact_url = false
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    
    address = """<span>Curitiba-PR, <strong>BRASIL</strong></span>
        <br>
        <span><i class="fas fa-envelope"></i> andersonmdcanteli@gmail.com</span>
      """

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"><i class="fas fa-envelope"></i> andersonmdcanteli@gmail.com</p>"""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
